### ISSUE TITLE
Remove Django code and review dependencies

### ISSUE THREAD

**Issue by fabiocerqueira** [denisra/pypular#5]

**Comment by lffsantos** [comment]
I was thinking of using django

**Comment by fabiocerqueira** [comment]
@lffsantos yes, could be a good option, but today we have 2 models codes:

https://github.com/denisra/pypular/blob/master/twitter_connector/models.py
https://github.com/denisra/pypular/blob/master/posts/models.py

If we decide use Django I think we should drop SQLAlchemy and use Django Models instead, but only one :D

**Comment by lffsantos** [comment]
yeah, i'm working in this. It almost ready, just more one tests and i do PR

**Comment by denisra** [comment]
Posts was supposed to be a diango app similar to a blog, where we would display each video on its own post.
But if we want to decouple the API/backend part, it probably makes sense to remove any reference to the django apps from this repo. We can then create another repo for the web/frontend part.

Thoughts?

**Comment by fabiocerqueira** [comment]
@lffsantos ok, finish it and we can talk more about what @denisra said :D

**Comment by fabiocerqueira** [comment]
@lffsantos did a lot of job in favor of we use django 👍
